version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    hostname: mosquitto
    volumes:
      - ./.services/mosquitto:/mosquitto
    expose:
        - "8883"
        - "9001"
    ports:
        - "8883:8883"
        - "9001:9001"
  mongo-local:
    image: mongo:7.0.1
    container_name: mongo-local
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo-local:27017/local --quiet
      interval: 10s
      timeout: 10s
      retries: 7
      start_period: 50s
    ports:
      - 27017:27017
    env_file:
      - ./.services/mongo/.env
    volumes: 
      - './.volumes/mongo:/data/db'
  
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    depends_on:
      mongo-local:
        condition: service_healthy
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.services/mongo-express/.env
  
  background-services:
    image: davidcuy/makeriot-background-services:dev
    container_name: background-services
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-local:
        condition: service_healthy
    restart: always
    env_file:
      - ./.services/background-services/.env
    environment:
      PYTHONUNBUFFERED: 1
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9890:15672
      - 8888:5672
    expose:
      - "8888"
    hostname: stats
    volumes:
      - ./.volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - type: bind
        source: ./.volumes/rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./.volumes/rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./.volumes/rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
  