version: '3'

services:
  api-internal-iot:
    image: iot-server
    container_name: iot-server
    depends_on:
      mongo-local:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - SQLITE_PATH=${SQLITE_PATH}
    ports:
      - 5000:5000
    volumes: 
      - '.:/code'
      - './.services/server/conf:/code/conf'
      - './.volumes/db:/code/db'
      - './.volumes/server/storage:/code/api/storage/local'
      - './.volumes/server/credentials/server:/code/api/storage/credentials/server'
      - './.volumes/server/credentials/clients:/code/api/storage/credentials/clients'
  mongo-local:
    image: mongo:7.0.1
    container_name: mongo-local
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo-local:27017/local --quiet
      interval: 10s
      timeout: 10s
      retries: 7
      start_period: 50s
    env_file:
      - ./.services/mongo/.env
    volumes: 
      - './.volumes/mongo:/data/db'
  
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    depends_on:
      mongo-local:
        condition: service_healthy
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.services/mongo-express/.env

