"""empty message

Revision ID: 081e4376640e
Revises: f610bf799e52
Create Date: 2022-02-26 03:06:36.599119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081e4376640e'
down_revision = 'f610bf799e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MqttTopics',
    sa.Column('IdMqttTopic', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdMqttTopic')
    )
    op.drop_table('Dumps')
    op.drop_table('Examples')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Examples',
    sa.Column('IdExample', sa.INTEGER(), nullable=False),
    sa.Column('Description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('IdExample')
    )
    op.create_table('Dumps',
    sa.Column('IdDump', sa.INTEGER(), nullable=False),
    sa.Column('Description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('IdDump')
    )
    op.drop_table('MqttTopics')
    # ### end Alembic commands ###
