"""empty message

Revision ID: 0915d1d25efe
Revises: 081e4376640e
Create Date: 2022-02-26 20:15:24.201646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0915d1d25efe'
down_revision = '081e4376640e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MqttTopics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MqttTopics', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
