"""empty message

Revision ID: 151c78dbf996
Revises: 50e8ea0faf89
Create Date: 2023-09-30 23:41:05.606872

"""
from alembic import op
import sqlalchemy as sa
from api.app.Data.Models import DeviceType


# revision identifiers, used by Alembic.
revision = '151c78dbf996'
down_revision = '50e8ea0faf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeviceTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_config', sa.Boolean(), nullable=True))
        t_device_types = sa.Table(
            'DeviceTypes',
            sa.MetaData(),
            sa.Column('IdDeviceType', sa.Integer()),
            sa.Column('name', sa.String()), # Old column.
            sa.Column('enabled_config', sa.Boolean())
        )

    # Use Alchemy's connection and transaction to noodle over the data.
    connection = op.get_bind()        
    connection.execute(t_device_types.update().where(t_device_types.c.name == 'MQTT').values(
        enabled_config=True
    ))
    connection.execute(t_device_types.update().where(t_device_types.c.name != 'MQTT').values(
        enabled_config=False
    ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeviceTypes', schema=None) as batch_op:
        batch_op.drop_column('enabled_config')

    # ### end Alembic commands ###
