"""empty message

Revision ID: 50e8ea0faf89
Revises: 06a1fdd84023
Create Date: 2022-06-26 01:12:27.577206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e8ea0faf89'
down_revision = '06a1fdd84023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Devices',
    sa.Column('IdDevice', sa.Integer(), nullable=False),
    sa.Column('IdDeviceType', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['IdDeviceType'], ['DeviceTypes.IdDeviceType'], ),
    sa.PrimaryKeyConstraint('IdDevice')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Devices')
    # ### end Alembic commands ###
