"""empty message

Revision ID: 8a47e533d235
Revises: 151c78dbf996
Create Date: 2023-10-08 23:26:08.569646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a47e533d235'
down_revision = '151c78dbf996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    cloud_providers_table = op.create_table('CloudProviders',
    sa.Column('IdCloudProvider', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdCloudProvider')
    )
    op.create_table('CloudConfigs',
    sa.Column('IdCloudConfig', sa.Integer(), nullable=False),
    sa.Column('IdCloudProvider', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['IdCloudProvider'], ['CloudProviders.IdCloudProvider'], ),
    sa.PrimaryKeyConstraint('IdCloudConfig')
    )

    op.bulk_insert(cloud_providers_table, [
        {'name': 'AWS (Amazon Web Services)'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CloudConfigs')
    op.drop_table('CloudProviders')
    # ### end Alembic commands ###
