name: Publish To DockerHub
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'environment'
        required: true
        options:
          - dev
          - qa
          - prod
jobs:
  push_to_registry:
    environment: "${{ github.event.inputs.environment }}"
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASS: "${{ secrets.DOCKER_PASSWORD }}"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ vars.DOCKERHUB_SPACE }}/${{ vars.DOCKER_REPOSITORY }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ vars.DOCKERHUB_SPACE }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.GITHUB_REF_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
